# This file is public domain, it can be freely copied without restrictions.
# SPDX-License-Identifier: CC0-1.0

TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES = $(shell pwd)/and_gate.v
MODULE = test_and_gate
TOPLEVEL = and_gate

include $(shell cocotb-config --makefiles)/Makefile.sim
